### ISSUE TITLE
SMACD

### ISSUE THREAD

**Issue by DaveR396** [neilmcguire/ninjatrader8#1]
Neil, I downloaded the indicators zip folder and attempted to import it into NT8. It through an error message that said the indicator was created with an older version of NT8 and would not work with the current version. My version of NT8 is 8.0.20.0
feel free to email me at dave@rushing.us  thanks!

**Comment by neilmcguire** [comment]
Added a wiki page with more detailed instructions, since downloading the repo as a .zip file does not allow it to be imported using Tools > Import NinjaScript AddOn.

[Installation page in Wiki](https://github.com/neilmcguire/ninjatrader8/wiki/Installing-the-SMACD-Indicator)
